### ISSUE TITLE
otelhttp: Record metrics on timed out requests

### ISSUE THREAD

**Issue by pellared** [open-telemetry/opentelemetry-go-contrib#4542] opened 2023-11-09 17:39 UTC
On an HTTP client implementation, I have a meter using the request context and I would like to keep track of HTTP timeouts, however, the metrics are ignored because of this timeout.

_Originally posted by @ravanscafi in https://github.com/open-telemetry/opentelemetry-go/issues/3618#issuecomment-1804264546_

We should do something like here: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/fe68fe96a73a70a27afad0772618d7b15b3aa124/instrumentation/google.golang.org/grpc/otelgrpc/stats_handler.go#L206-L235

**Comment by carrbs** [comment] 2023-11-14 21:39
Would it be possible to include some additional context for someone who is looking to pick up a "good first issue"? Potentially a way to reproduce the bug/scenario?

It appears we can likely copy (or generalize to share between the two) the `withoutCancel` flow and call it ([here](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/handler.go#L229)) before calling the next middleware/handler in the chain, so it doesn't cancel the context prematurely, something like:
```go
// instrumentation/net/http/otelhttp/handler.go:232
ctxWithoutCancel := withoutCancel(ctx)
next.ServeHTTP(w, r.WithContext(ctxWithoutCancel))
```
But I'm not certain that's the requested fix 🤔... (likely bc most of this is very new to me 😁).

**Comment by pellared** [comment] 2023-11-15 10:16
> Would it be possible to include some additional context for someone who is looking to pick up a "good first issue"? Potentially a way to reproduce the bug/scenario?

I see two ways

First one, to cancel using an HTTP Client. See: https://pkg.go.dev/net/http#Request.Context

> For incoming server requests, the context is canceled when the client's connection closes,

Second one, to cancel through HTTP Server itself.  See `Server.BaseContext` : https://pkg.go.dev/net/http#Server

> BaseContext optionally specifies a function that returns the base context for incoming requests on this server.



> It appears we can likely copy (or generalize to share between the two) the withoutCancel flow and call it ([here](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/handler.go#L229)) before calling the next middleware/handler in the chain, so it doesn't cancel the context prematurely, something like:

The derived context created via `withoutCancel` should be only used for recording measurements here: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/7469f6101b0b99a233f807797e225225a8cc7fc3/instrumentation/net/http/otelhttp/handler.go#L239-L245. Terefore, I would rather create a context using `withoutCancel` somewhere here: https://github.com/open-telemetry/opentelemetry-go-contrib/blob/7469f6101b0b99a233f807797e225225a8cc7fc3/instrumentation/net/http/otelhttp/handler.go#L233.

**Comment by shuwpan** [comment] 2023-11-16 23:58
Hi @carrbs and @pellared, 

I am new to go repo, I saw this is a "good first issue" so I came in.
Let me try to summarize my understanding for this issue.
1. We want to be able to count how many http calls are timed out and put that number in metrics.
2. I assume we should implement something similar to the code snippet shown in the description area. 

Here are my questions
1. How to reproduce the issue ? 
    a. Write a sample http server + simple http client, instrument both
    b. then somehow make the call timeout 
2. Where should the fixing code go ? I saw some suggestions in comment area. (but no having much brackgroud, not quite getting it)

Thanks,
Shuwen

**Comment by pellared** [comment] 2023-11-17 07:31
This issue is good for "newcomers", but not for Go novices.

**Comment by shuwpan** [comment] 2023-11-17 16:02
@pellared , I mean go repo, not go itself

**Comment by carrbs** [comment] 2023-11-27 23:08
Hi @pellared, I added a WIP PR to take a crack at this. Would it be good to assign this to me so there isn't duplicative effort?

**Comment by carrbs** [comment] 2023-12-27 21:42
@pellared, I think this should be closed since we'll be [handling this case](https://github.com/open-telemetry/opentelemetry-go/pull/4671) lower level now?

**Closed** 2024-01-02 17:09 UTC
Labels: bug, good first issue, help wanted, area: instrumentation, instrumentation: otelhttp
