### ISSUE TITLE
Failed to build due to Beego dependency issues

### ISSUE THREAD

**Issue by rltoSD** [open-telemetry/opentelemetry-go-contrib#1386] opened 2021-11-02 23:15 UTC
![image](https://user-images.githubusercontent.com/50217652/139964304-48dbdda6-5139-4317-a137-e0ae4c3a40e0.png)

I was setting up my local development environment for openetelemetry-go-contrib and encountered an issue with building due to a dependency issue related to Beego. It seems that the original tag has been deleted. 

Utilizing Go 1.17.2, MacOS Big Sur x86

**Comment by hyunuk** [comment] 2021-11-04 15:56
@Aneurysm9 Would you assign this to me? I would take it!

**Comment by hyunuk** [comment] 2021-11-05 01:09
I once solved this issue using replace directive but @Aneurysm9 wants to moving the entire instrumentation and changing all references so that there are no more references to astaxie left.

So I renamed every `astaxie` to `beego`, tested but it failed.

The problem is in github.com/beego/beego v1.12.3. In this version, go.mod has the module name as `github.com/astaxie/beego`, which should be `github.com/beego/beego`.

So I had to left some of the `import` statement `github.com/astaxie/beego` since it actually import the location from `github.com/beego/beego` , but the module name is `astaxie/beego`.

Another way that I could suggest is upgrading the version of beego. However, this v1.12.3 is the latest version of beego v1, and from v2, they changed the architecture so if we want to use the v1's api, we should import "github.com/beego/beego/v2/adapter" . I'm not sure the usage is 100% compatible. I changed the current dependency, `astaxie/beego` to `beego/beego/v2/adapter` and it worked well.

**Comment by hyunuk** [comment] 2021-11-08 23:14
https://github.com/mattn/go-sqlite3/issues/975#issuecomment-958636328

> @mattn I'm guessing the reason this just become an issue recently is because the v2 tags were deleted from this repo. Is that correct? If so, would you be able to re-create them for the same commits? That way people using "direct" at least won't get failed builds. (This is orthogonal to retracting the v2 releases.)

This issue is resolved and working fine now.

**Closed** 2021-11-09 00:25 UTC
