### ISSUE TITLE
protobuf crash on span End

### ISSUE THREAD

**Issue by schmurfy** [open-telemetry/opentelemetry-go-contrib#556] opened 2021-01-19 15:21 UTC
We are currently testing otel (with uptace-go) on our microservices and ran into a segfault which occurs everytime a service is called, we are still investigating the exact conditions but in any case it should not result in a segfault.

Here is what we get:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
```

and right after that:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcb4b0a]

goroutine 1197 [running]:
go.opentelemetry.io/otel/sdk/trace.(*span).End(0xc000144a80, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.opentelemetry.io/otel/sdk@v0.15.0/trace/span.go:158 +0x199
panic(0x145a380, 0x1faaa00)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/gogo/protobuf/types.(*Empty).MarshalToSizedBuffer(...)
	/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/types/empty.pb.go:194
github.com/gogo/protobuf/types.(*Empty).Marshal(0x0, 0x15bb820, 0x0, 0x7f05cbc105f0, 0x0, 0x1)
	/go/pkg/mod/github.com/gogo/protobuf@v1.3.1/types/empty.pb.go:177 +0x6a
google.golang.org/protobuf/internal/impl.legacyMarshal(0x17c4880, 0xc000209ee0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000893200, 0x8595e2, ...)
	/go/pkg/mod/google.golang.org/protobuf@v1.25.0/internal/impl/legacy_message.go:391 +0xb0
google.golang.org/protobuf/proto.MarshalOptions.size(0xc000000000, 0x17c4880, 0xc000209ee0, 0x0)
	/go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/size.go:43 +0xcf
google.golang.org/protobuf/proto.MarshalOptions.Size(0x1000000, 0x177f040, 0xc000209ee0, 0xc000209ee0)
	/go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/size.go:26 +0x55
google.golang.org/protobuf/proto.Size(...)
	/go/pkg/mod/google.golang.org/protobuf@v1.25.0/proto/size.go:16
github.com/golang/protobuf/proto.Size(0x7f05cbc10580, 0x0, 0x0)
	/go/pkg/mod/github.com/golang/protobuf@v1.4.3/proto/wire.go:18 +0x69
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.messageType.Event(0x16174be, 0xc, 0x8, 0x0, 0x160d63a, 0x4, 0x0, 0x0, 0x17b1640, 0xc000460600, ...)
	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.15.1/interceptor.go:52 +0x20e
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1(0x17b1640, 0xc000460600, 0x15b70a0, 0xc0005bb6d0, 0xc00027cf00, 0xc00027d020, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.15.1/interceptor.go:341 +0xcc5
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x17b1640, 0xc0004601b0, 0x15b70a0, 0xc0005bb6d0, 0xc00098d900, 0x0, 0xc0006f2b30, 0x40e358)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:25 +0x63
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x17b1640, 0xc0004601b0, 0x15b70a0, 0xc0005bb6d0, 0xc00027cf00, 0xc00027cf20, 0xc0006f2ba0, 0x54a106, 0x15343a0, 0xc0004601b0)
	/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.0/chain.go:34 +0xd7
github.com/birotaio/backend-services/generated_pb/bike._BikeService_SetAutoDiags_Handler(0x1606960, 0xc000124760, 0x17b1640, 0xc0004601b0, 0xc000509e00, 0xc000479c80, 0x17b1640, 0xc0004601b0, 0xc000589c30, 0xe)
	/tmp/build/80754af9/backend-services/bike/generated_pb/bike/bike.pb.go:16347 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000183c00, 0x17bfde0, 0xc0001a4180, 0xc00098d900, 0xc000479dd0, 0x1fc0078, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1210 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000183c00, 0x17bfde0, 0xc0001a4180, 0xc00098d900, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:1533 +0xd05
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0002747a0, 0xc000183c00, 0x17bfde0, 0xc0001a4180, 0xc00098d900)
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:871 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.34.0/server.go:869 +0x1fd
```

The project is running uptrace-go version 0.6.1 and otel 0.15.
My original issue is here: https://github.com/uptrace/uptrace-go/issues/63

**Comment by jemisonf** [comment] 2021-01-19 23:48
I'm seeing an issue with the `proto.Size` call as well working on [ArgoCD](https://github.com/argoproj/argo-cd), where the method panics if it sees an optional field that isn't a pointer. I think the issue is basically the same though, which is that the size method seems to panic a lot and any issues there will cause the entire request to fail. I'm pretty sure the fix from the [uptrace fork from the linked issue](https://github.com/uptrace/opentelemetry-go-contrib/commit/f82c0f8a19f7797228c8b06cc3f318eda628397b) would work for me as well.

**Comment by schmurfy** [comment] 2021-01-20 08:09
after some digging we found out what was causing the issue but I am not really sure why or how:

The implementation of the grpc method was supposed to return an object but all it did was:
```go
return nil, nil
```

When returning a proper object it fixes the issue, I don't know how grpc is supposed to handle nil value if permitted at all but this was the trigger in our usecase.

**Comment by jemisonf** [comment] 2021-02-03 22:25
Hi @MrAlias, I'm curious if there's a plan on your end for how to implement a fix for this? I'm trying to decide if I should find a workaround on the client-side or wait for an update here. I'm not sure I can get to it super fast but if the issue is no one being able to work on the fix I can potentially help.

**Comment by XSAM** [comment] 2021-02-16 05:50
The [original issue](https://github.com/uptrace/uptrace-go/issues/63#issuecomment-774924408) seems been solved. Feel free to reopen if you have further questions.

**Closed** 2021-02-16 05:50 UTC
Labels: area: instrumentation, bug
