### ISSUE TITLE
Error logs coming for http: superfluous response.WriteHeader call when using otelhttp handler and http.Flusher interface

### ISSUE THREAD

**Issue by niallnsec** [open-telemetry/opentelemetry-go-contrib#6073] opened 2024-09-04 11:34 UTC
### Description

Same bug as #6053 which has not been fixed fully. When using the Flusher interface, for example for SSE, the bug still manifests.

### Environment

- OS: macOS
- Architecture: arm64
- Go Version: 1.23.0
- `otelhttp` version: main (06ace3e8e57f)

### Steps To Reproduce

1. Using this code:

```
package main

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
)

func main() {
	handler := http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		flusher, ok := w.(http.Flusher)
		if !ok {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}

		w.Header().Set("Content-Type", "text/event-stream")
		w.Header().Set("Cache-Control", "no-cache")
		w.Header().Set("Connection", "keep-alive")

		t := time.NewTicker(time.Second * 10)
		defer t.Stop()

		_, err := w.Write(formatSSE("ping", ""))
		if err != nil {
			w.WriteHeader(http.StatusInternalServerError)
			return
		}
		flusher.Flush()

		for {
			select {
			case <-r.Context().Done():
				return
			case <-t.C:
				_, err := w.Write(formatSSE("ping", ""))
				if err != nil {
					w.WriteHeader(http.StatusInternalServerError)
					return
				}
				flusher.Flush()
			}
		}
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("Hello, World!"))
	})

	otelHandler := otelhttp.NewHandler(handler, "simple-server")

	server := http.Server{
		Addr:    ":8080",
		Handler: otelHandler,
	}

	if err := server.ListenAndServe(); http.ErrServerClosed != err {
		fmt.Printf("Error: %v\n", err)
	}

	fmt.Println("Server stopped")
}

func formatSSE(event string, data string) []byte {
	eventPayload := "event: " + event + "\n"
	dataLines := strings.Split(data, "\n")
	for _, line := range dataLines {
		eventPayload = eventPayload + "data: " + line + "\n"
	}
	return []byte(eventPayload + "\n")
}
```

3. Run:

```
go get go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@main

go run main.go

curl http://localhost:8080
```

4. See error ... (Sent for each SSE event sent to the client)

```
2024/09/04 12:27:52 http: superfluous response.WriteHeader call from go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp/internal/request.(*RespWriterWrapper).writeHeader (resp_writer_wrapper.go:80)
```

### Expected behavior

No output

**Comment by dmathieu** [comment] 2024-09-04 13:38
Duplicate of https://github.com/open-telemetry/opentelemetry-go-contrib/issues/6053

**Comment by niallnsec** [comment] 2024-09-04 13:40
@dmathieu #6053 is closed but the issue is not fixed as stated in that issue, this is not a duplicate.

**Comment by niallnsec** [comment] 2024-09-04 13:45
The issue specifically relates to the case when the http.Flusher interface is used, which was not accounted for in the fix for #6053 hence the new report.

My report above gives you a reproducible demonstration of this bug using the lates commit of this repository, not the last release, confirming that the issue is not fixed by 54d6916.

Please re-open this issue.

**Comment by amanakin** [comment] 2024-09-04 13:47
I think we just can add the same check as #6053 here:
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/net/http/otelhttp/internal/request/resp_writer_wrapper.go#L85

**Comment by dmathieu** [comment] 2024-09-04 14:00
My bad, sorry. Feel free to open a PR with the fix and a test case.

**Closed** 2024-09-05 17:34 UTC
Labels: bug, area: instrumentation, instrumentation: otelhttp
