### ISSUE TITLE
Feature Request: Use Kubernetes Client for EKS Resource Detector

### ISSUE THREAD

**Issue by wilguo** [open-telemetry/opentelemetry-go-contrib#478] opened 2020-12-03 23:55 UTC
**Is your feature request related to a problem? Please describe.**
No, this feature request is not related to a problem or issue. It is an enhancement for the EKS resource detector in order to prevent duplicate code upstream.

**Describe the solution you'd like**
The EKS resource detector should use the Kubernetes client library for getting the cluster name.

**Additional context**
The original PR for the EKS resource detector is here https://github.com/open-telemetry/opentelemetry-go-contrib/pull/465, and the comments to request to use the Kubernetes client library can be found here: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/465#discussion_r532961619, https://github.com/open-telemetry/opentelemetry-go-contrib/pull/465#discussion_r535499096.

**Comment by nchetan** [comment] 2021-04-24 00:01
@Aneurysm9 Is this still open/available? There seems to be a merged branch, Hence the question.

**Comment by xukaren** [comment] 2021-05-12 22:08
Hi @nchetan @Aneurysm9 is this being worked on? If not I would be happy to take a look

**Comment by chetanrz** [comment] 2021-05-13 16:10
Hey @xukaren I did not receive any response on this from @Aneurysm9. Hence I did not take this up. 
Please ensure that the code has not been merged already before taking this up. No point in duplicating the effort ;)

**Comment by nchetan** [comment] 2021-05-13 16:11
Hey @xukaren I did not receive any response on this from @Aneurysm9. Hence I did not take this up. 
Please ensure that the code has not been merged already before taking this up. No point in duplicating the effort ;)

**Comment by xukaren** [comment] 2021-05-13 17:10
Hi @nchetan, from my understanding, the ask is for a further enhancement to the merged PR. The issue should still be open - would you like to take it?

**Comment by xukaren** [comment] 2021-05-13 17:38
Hi @nchetan, I discussed this offline with @Aneurysm9, and the issue is still open. The issue is asking for a further enhancement to #465. Would you be work on it?

**Comment by chetanrz** [comment] 2021-05-13 17:46
Hey @xukaren, Thanks for following up on this one. I have already started working on other things now. Please go ahead and take it on if you like.
Best

**Comment by nchetan** [comment] 2021-05-13 17:47
Hey @xukaren, Thanks for following up on this one. I have already started working on other things now. Please go ahead and take it on if you like.
Best

**Comment by xukaren** [comment] 2021-05-14 04:26
@dashpole @MrAlias Could you clarify the scope of this issue? For example, what pod metadata should be fetched? From my understanding the only ones needed by the AWS EKS resource detector are ContainerID and ClusterName. And the GKE resource detector doesn't need anything (as they rely on a separate Go package). Besides these two attributes, is there anything that I should cover? Also I have looked at other language repositories and haven't found anything similar. Would you have any pointers on how to get started? Thank you!

**Comment by dashpole** [comment] 2021-05-14 13:27
The suggestion is to use kubernetes' [client-go](https://github.com/kubernetes/client-go) library to get the cluster name configmap instead of making GET calls directly.

**Comment by Raul9595** [comment] 2021-06-15 19:27
Hi! I had taken up the issue and worked on it after discussing it with @xyira offline. I believe this issue can be closed now since the mentioned pull request provides the necessary enhancement.

**Closed** 2021-06-15 19:58 UTC
Labels: area: instrumentation, good first issue, help wanted, release:after-ga
