### ISSUE TITLE
Request to Add Attributes for SNS attributes

### ISSUE THREAD

**Issue by mauriciocm9** [open-telemetry/opentelemetry-go-contrib#3350] opened 2023-02-03 21:08 UTC
Hello, I want to add the attributes for some services like SNS, Kinesis and others. Is someone already working on this or is there something that I have to consider? Thank you in advance.

**Comment by pragmaticivan** [comment] 2024-12-01 22:58
Duplicated? https://github.com/open-telemetry/opentelemetry-go-contrib/issues/1613

cc @Aneurysm9

**Comment by dmathieu** [comment] 2024-12-02 08:11
Closing as duplicate of https://github.com/open-telemetry/opentelemetry-go-contrib/issues/1613.

**Closed by dmathieu** 2024-12-02 08:11 UTC
Labels: enhancement, area: instrumentation
