### ISSUE TITLE
latest version of log bridge is not compiling

### ISSUE THREAD

**Issue by Ignaciojeria** [open-telemetry/opentelemetry-go-contrib#6239] opened 2024-10-13 14:26 UTC
### Description
When I run my app using the latest versions of OpenTelemetry contributions, it throws the following error:
..\..\..\go\pkg\mod\go.opentelemetry.io\contrib\bridges\otelslog@v0.5.0\handler.go:207:31: cannot use record (variable of type "go.opentelemetry.io/otel/log".Record) as "go.opentelemetry.io/otel/log".EnabledParameters value in argument to h.logger.Enabled
![image](https://github.com/user-attachments/assets/d08d7168-2875-4f73-84d7-481f4a18b65c)

### Environment

My go mod :
module multi-folder-components

go 1.22.0

require (
	github.com/Ignaciojeria/einar-ioc/v2 v2.4.0
	github.com/go-playground/validator/v10 v10.22.1
	github.com/go-slog/otelslog v0.1.0
	github.com/hellofresh/health-go/v5 v5.5.3
	github.com/joho/godotenv v1.5.1
	github.com/labstack/echo/v4 v4.12.0
	go.opentelemetry.io/contrib/bridges/otelslog v0.5.0
	go.opentelemetry.io/otel v1.31.0
	go.opentelemetry.io/otel/exporters/otlp/otlplog/otlploggrpc v0.7.0
	go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v1.31.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.31.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.31.0
	go.opentelemetry.io/otel/metric v1.31.0
	go.opentelemetry.io/otel/sdk v1.31.0
	go.opentelemetry.io/otel/sdk/log v0.7.0
	go.opentelemetry.io/otel/sdk/metric v1.31.0
	go.opentelemetry.io/otel/trace v1.31.0
	google.golang.org/grpc v1.67.1
)

require (
	github.com/cenkalti/backoff/v4 v4.3.0 // indirect
	github.com/emirpasic/gods v1.18.1 // indirect
	github.com/gabriel-vasile/mimetype v1.4.5 // indirect
	github.com/go-logr/logr v1.4.2 // indirect
	github.com/go-logr/stdr v1.2.2 // indirect
	github.com/go-playground/locales v0.14.1 // indirect
	github.com/go-playground/universal-translator v0.18.1 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/grpc-ecosystem/grpc-gateway/v2 v2.22.0 // indirect
	github.com/heimdalr/dag v1.5.0 // indirect
	github.com/labstack/gommon v0.4.2 // indirect
	github.com/leodido/go-urn v1.4.0 // indirect
	github.com/mattn/go-colorable v0.1.13 // indirect
	github.com/mattn/go-isatty v0.0.20 // indirect
	github.com/valyala/bytebufferpool v1.0.0 // indirect
	github.com/valyala/fasttemplate v1.2.2 // indirect
	go.opentelemetry.io/otel/log v0.7.0 // indirect
	go.opentelemetry.io/proto/otlp v1.3.1 // indirect
	golang.org/x/crypto v0.28.0 // indirect
	golang.org/x/net v0.30.0 // indirect
	golang.org/x/sys v0.26.0 // indirect
	golang.org/x/text v0.19.0 // indirect
	google.golang.org/genproto/googleapis/api v0.0.0-20241007155032-5fefd90f89a9 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20241007155032-5fefd90f89a9 // indirect
	google.golang.org/protobuf v1.35.1 // indirect
)

### Steps To Reproduce
$ go install github.com/Ignaciojeria/einar@v1.44.0
$ einar install observability
$ go run main.go

EinarCLI:
https://ignaciojeria.github.io/
After this issue, I learned that it is critical to create a mechanism to test and validate versions before upgrading them. I’m going to add that to my backlog.

**Comment by duongphuhiep** [comment] 2024-10-13 18:18
hmm the problem maybe deeper than that? why didn't the CI/CD fail when the project doesn't compile? 
![image](https://github.com/user-attachments/assets/88f3af90-ab1c-4fa9-ac29-b32e5d01f5ed)

or maybe why not write some unit tests for this `handler.go` evens if a silly one?

**Comment by elkcert** [comment] 2024-10-14 01:11
Same issue. Think it has something to do with this https://github.com/open-telemetry/opentelemetry-go/pull/5791

**Comment by MrAlias** [comment] 2024-10-14 02:42
Thank you for your interest in the project. The release for the slog bridge has been delayed. It should be out in a day or so and resolve this.

**Comment by elkcert** [comment] 2024-10-14 08:35
> Thank you for your interest in the project. The release for the slog bridge has been delayed. It should be out in a day or so and resolve this.

The issue is present when using the zap bridge as well:

[...]\go\pkg\mod\go.opentelemetry.io\contrib\bridges\otelzap@v0.5.0\core.go:145:48: cannot use r (variable of type "go.opentelemetry.io/otel/log".Record) as "go.opentelemetry.io/otel/log".EnabledParameters value in argument to o.logger.Enabled

[...]\go\pkg\mod\go.opentelemetry.io\contrib\bridges\otelzap@v0.5.0\core.go:187:42: cannot use r (variable of type "go.opentelemetry.io/otel/log".Record) as "go.opentelemetry.io/otel/log".EnabledParameters value in argument to logger.Enabled

**Comment by dmathieu** [comment] 2024-10-14 09:21
All packages in this repository are released at the same time. This will be resolved by #6243.

**Closed** 2024-10-14 15:29 UTC
Labels: bug

**Comment by MrAlias** [comment] 2024-10-14 18:00
@Ignaciojeria this should be resolved by upgrading to the latest version of the bridges. Please verify and re-open if you are still having issues. Sorry about the disruption.

**Comment by Ignaciojeria** [comment] 2024-10-15 00:56
I was at work and didn't have time to validate it since I usually make progress on EinarCLI in my free time. I just tested it, and it worked perfectly. Thank you so much! I'll improve the dependency versioning on my end and test the updates suggested by Dependabot before making a new release. Thanks again for your contribution to the community with your work. 🚀
