### ISSUE TITLE
otelgrpc: Consider using `stats.Handler` instead of interceptor

### ISSUE THREAD

**Issue by Aneurysm9** [open-telemetry/opentelemetry-go-contrib#3169] opened 2023-01-19 00:02 UTC
See [comment](https://github.com/open-telemetry/opentelemetry-go-contrib/issues/3165#issuecomment-1386010160) on #3165.

**Comment by dashpole** [comment] 2023-01-19 15:40
+1.  This was something that came up when discussing instrumentation with the gRPC-go team at Google.

**Comment by MrAlias** [comment] 2023-01-20 16:20
This looks like a duplicate of https://github.com/open-telemetry/opentelemetry-go-contrib/issues/197

**Closed** 2023-11-07 07:34 UTC
Labels: duplicate
