### ISSUE TITLE
Migrating from opentracing Jaeger to opentelemetry

### ISSUE THREAD

**Issue by dino-ma** [open-telemetry/opentelemetry-go-contrib#1878] opened 2022-03-01 12:19 UTC
I'd like to ask how to set probability sampling through opentelemetry. Previously, it was implemented through Jaeger's collector configuration by the client to request the interface of the agent. Now, opentelemetry will automatically implement this strategy. Don't we need to configure the service name and URL address?

**Comment by dino-ma** [comment] 2022-03-01 12:24
And where can Jaeger's bufferflush interval be set?

**Comment by MrAlias** [comment] 2022-03-02 00:22
Closing as this looks like a duplicate of https://github.com/open-telemetry/opentelemetry-go/issues/2642

**Closed by MrAlias** 2022-03-02 00:22 UTC
Labels: enhancement, area: instrumentation
